
# HARDPASS (Pi Zero W / RNDIS gadget) attach
notify 100 {
	match "system"		"IFNET";
	match "subsystem"	"ue0";
	match "type"		"ATTACH";
	action "/usr/local/sbin/hardpass-net attach &";
};

# HARDPASS (Pi Zero W / RNDIS gadget) detach
notify 100 {
	match "system"		"IFNET";
	match "subsystem"	"ue0";
	match "type"		"DETACH";
	action "/usr/local/sbin/hardpass-net detach &";
};
